source "https://rubygems.org"

gem "addressable"
gem "colorize"
gem "filesize"
gem "ruby-xz"

group :development, :test do
  gem "rake"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
end
